name: Release
on:
  push:
    tags:
    - 'v*'
env:
  GO_VERSION: stable

jobs:
  build_for_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
          build-essential
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build amd64
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-linux
        path: bsky-linux-*.zip

  build_for_macos:
    name: Build for MacOS
    runs-on: macos-13 # Use macos-13 to build darwin/amd64. macos-latest is arm64.
    steps:
    - name: Install build dependencies
      run: brew install coreutils
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build amd64
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-darwin
        path: bsky-darwin-*.zip

  build_for_windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - name: Install build dependencies
      run: choco install zip
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build amd64
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: amd64
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows
        path: bsky-windows-*.zip

  release:
    name: Draft Release
    needs:
      - build_for_linux
      - build_for_macos
      - build_for_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: bsky ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          generate_release_notes: true
          files: dist-*/bsky*.*
